cargo-features = ["edition2021"]
[package]
name = "liquid_alloc"
version = "1.0.0-rc2"
authors = ["vita-dounai <lichenxi.webank@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wee_alloc = { version = "0.4.2", default-features = false }

[features]
default = ["std"]
std = []
